### ISSUE TITLE
[Feature Request]: Add option to specify tag for which version of ha-bridge to use

### ISSUE THREAD

**Issue by devdems** [linuxserver/docker-habridge#13]
Add availability to use different versions of bwssytems/ha-bridge. 

For example the tag would default to latest but it also could be specified by a variable.

This comes from the fact that there were a lot of improvements made for 5.3.1 but from the looks of it, the project has been stalled.
https://github.com/bwssytems/ha-bridge/releases/tag/v5.3.1RC1

**Comment by tobbenb** [comment]
We already tag the version of HA-bridge, so all you need to do is to check docker hub for the tag you want.

We only build releases and not RC/beta, so they will not be in our container.

**Comment by devdems** [comment]
It was meant to add a variable to give users an option to use RC release. What you are mentioning does not help.

**Comment by tobbenb** [comment]
I already answered that we are not going to add a tag for development builds.

It doesn't look like the development have been done at lightning speed before either, so he will probably release a new version at one point.
