### ISSUE TITLE
Container takes 400% CPU on Raspberry Pi4 (likely due to Alpine bug)

### ISSUE THREAD

**Issue by thmang82** [linuxserver/docker-habridge#15]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
docker should start the container and software run normally.

## Current Behavior
Container takes 400% cpu load on Raspberry PI4

Issue seems to come from a bug in the time handling inside the latest Alpine Linux (see log output)
Postgress container e.g. had also issues with this (log time years off and not healing itself, DB not starting)

Going back to linuxserver/habridge:arm32v7-version-v5.3.0 solves the issue. But this is no nice solution to stick to some old version.

## Steps to Reproduce
Download the latest image and start it.

## Environment
**OS:** Raspbian
**CPU architecture:** arm32
**How docker service was installed:**
Official Docker install script.

## Command used to create docker container (run/create/compose/screenshot)

 habridge:
    image: linuxserver/habridge
    container_name: habridge
    restart: always
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    ports:
      - "80:80"
      - "50000:50000"
    volumes:
      - /data/habridge:/config

## Docker logs

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
OpenJDK Zero VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
2067-02-05 00:22:32,000 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge startup sequence...

Log stopes at that point! Container hangs with consuming all the CPU!

**Comment by aptalca** [comment]
post a full log

**Comment by thmang82** [comment]
Full Log? The log is not any longer. Process hangs at 100%
If you do not believe me, just start the container ...

**Comment by Roxedus** [comment]
A full log has our logo on the top.
