### ISSUE TITLE
No updates since February?

### ISSUE THREAD

**Issue by srd424** [linuxserver/docker-habridge#17]
This package doesn't seem to have been rebuilt since Feb - I'm sure there have been changes to the base image since then. Is the CI/CD system stuck for this image for some reason?

**Comment by thespad** [comment]
Looks like the package triggers got disabled by Github, I've re-enabled them so the builds should run again.

**Comment by thespad** [comment]
Looks like there's an issue with the build pulling the latest release, which is likely what caused github to disable the triggers. Will need to look into it.
