### ISSUE TITLE
Alexa can't find Habridge

### ISSUE THREAD

**Issue by xundre** [linuxserver/docker-habridge#4]
Running this on qnap container station but alexa can't discover devices, web UI works find

**Comment by tobbenb** [comment]
I don't run Alexa, but I think habridge needs to run on port 80 for Alexa to be able to talk to habridge.

Also, you need a gen 1 echo for Alexa to find habridge on the network. It's mentioned in the Readme of habridge (Not our Readme)

**Comment by xundre** [comment]
I had it running previously on a raspberry pi which died, so figured i'll covert it to a virtual server on my NAS. It worked find on port 8082 but for some reason cannot be detected with on the virtual server. I am using a first generation echo.

**Comment by tobbenb** [comment]
I don't know how habridge and alexa talk to each other, so hard to troubleshoot this. But try setting the container to use host network instead of bridge (--net=host)

**Comment by homerr** [comment]
Closing, if using --net=host did not work then re-open and we'll see if we can be of any more help. However the chances are, if Alexa needs Port 80 and you're running this on a NAS then the webui of the NAS will be occupying port 80. You may need to run this on a new Pi if you want this functionality.
