### ISSUE TITLE
Do not use Home Assistant logo for habridge inside Unraid Community Applications

### ISSUE THREAD

**Issue by balloob** [linuxserver/docker-habridge#7]
To avoid confusion, please do not use the Home Assistant logo for other products.

This is the current screenshot from Unraid Community Applications:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/1444314/59625576-833dea80-90ee-11e9-8af3-6e2c016a6b4d.png">

**Comment by tobbenb** [comment]
Sorry about that. We'll fix it.

**Comment by balloob** [comment]
Thanks!
